#!/bin/bash -ex

FRAMEPATH=$1
NAME=${FRAMEPATH##*/} # remove everything before and including last slash

packer build \
	-var "framework=$1" \
	-var "source_ami=$2" \
	-var "name=$NAME" \
	packer_ami.json
